main: x.naxdy.lms.LastManStanding
name: HcLastManStanding
version: 0.1a
author: Naxdy
description: LMS
commands:
  match:
    description: Start a new match
    usage: /match
    permission-message: Unknown command! Type "/help" for help.
  who:
    description: List all players
    usage: /match
    aliases: [list,ls]
    permission-message: Unknown command! Type "/help" for help.
  help:
    description: List cmd
    usage: /help
    aliases: [me,tell,msg,m,w,whisper,cmds,commands]
    permission-message: Unknown command! Type "/help" for help.