main: x.naxdy.lms.LastManStanding
name: LastManStanding
version: 1.0
author: Naxdy
description: LMS
commands:
  match:
    description: Start a new match
    usage: /match
    permission-message: Your permissions are messed up.
  who:
    description: List all players
    usage: /match
    aliases: [list,ls]
    permission-message: Your permissions are messed up.
  lms:
    description: Displays plugin info
    usage: /lms
    permission-message: Your permissions are messed up.